// <auto-generated />
using System;
using AspireApp1.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspireApp1.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241113081751_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("AspireApp1.Models.Entities.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2024, 11, 13, 16, 17, 51, 158, DateTimeKind.Local).AddTicks(691),
                            Description = "This is product 1",
                            Price = 100.0,
                            ProductName = "Product 1",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2024, 11, 13, 16, 17, 51, 158, DateTimeKind.Local).AddTicks(692),
                            Description = "This is product 2",
                            Price = 200.0,
                            ProductName = "Product 2",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            CreateTime = new DateTime(2024, 11, 13, 16, 17, 51, 158, DateTimeKind.Local).AddTicks(694),
                            Description = "This is product 3",
                            Price = 300.0,
                            ProductName = "Product 3",
                            Quantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
